"""
Introduction to Machine Learning

Lab 3: Kernel regression

TODO: Add your information here.
    IMPORTANT: Please ensure this script
    (1) Run script_lab4.py on Python >=3.6;
    (2) No errors;
    (3) Finish in tolerable time on a single CPU (e.g., <=10 mins);
    (4) Do not add any additional package or lib
Student name(s): 黄浩博
Student ID(s): 2024201630
"""

import copy
import numpy as np
import matplotlib.pyplot as plt
# don't add any other packages


# data simulator and testing function (Don't change them)
def polynomial_data_simulator(n_train: int = 50,
                              n_test: int = 10,
                              order: int = 5,
                              v_noise: float = 1,
                              r_seed: int = 42) -> dict:
    """
    Simulate the training and testing data generated by a polynomial model
    """
    x_train = 4 * (np.random.RandomState(r_seed).rand(n_train) - 0.5)
    X_train = np.array([x_train ** d for d in range(order)]).T
    x_test = 5 * (np.random.RandomState(r_seed).rand(n_test) - 0.5)
    X_test = np.array([x_test ** d for d in range(order)]).T
    weights = np.random.RandomState(r_seed).randn(order, 1)
    y_train = X_train @ weights + v_noise * np.random.RandomState(r_seed).randn(n_train, 1)
    y_test = X_test @ weights + v_noise * np.random.RandomState(r_seed).randn(n_test, 1)
    data = {'train': [np.expand_dims(x_train, axis=1), y_train],
            'test': [np.expand_dims(x_test, axis=1), y_test],
            'real': weights}
    return data


def visualization_curves(weights: np.ndarray, label: str, curve_type: str):
    landmarks = 5 * (np.arange(0, 100) / 100 - 0.5)
    order = weights.shape[0]
    curve = np.array([landmarks ** d for d in range(order)]).T @ weights
    plt.plot(landmarks, curve, curve_type, label=label)


def visualization_points(x: np.ndarray, y: np.ndarray, label: str, point_type: str):
    plt.plot(x, y, point_type, label=label)


def visualization_kernel_curves(alpha: np.ndarray, x_train: np.ndarray,
                                k_type: str, h: float, label: str, curve_type: str, normalize: bool = False):
    landmarks = 5 * (np.arange(0, 100) / 100 - 0.5)
    kappa = kernel(x=x_train, y=np.expand_dims(landmarks, axis=1), k_type=k_type, bandwidth=h)
    if normalize:
        curve = (kappa / np.sum(kappa + 1e-10, axis=1, keepdims=True)) @ alpha
    else:
        curve = kappa @ alpha
    plt.plot(landmarks, curve, curve_type, label=label)


def mse(x: np.ndarray, x_est: np.ndarray) -> float:
    return np.sum((x - x_est) ** 2) / x.shape[0]


# Task 1: Implement typical valid kernel functions and the Nadaraya–Watson estimator
def p_distance(x: np.ndarray, y: np.ndarray, p: int = 2):
    return np.sum(np.abs(np.expand_dims(x, axis=1) - np.expand_dims(y, axis=0)) ** p, axis=2)


def kernel(x: np.ndarray, y: np.ndarray = None, k_type: str = 'rbf', bandwidth: float = 1.0) -> np.ndarray:
    if y is None:
        y = copy.deepcopy(x)

    if k_type == 'rbf':
        dist_sq = p_distance(y, x, p=2)
        return np.exp(-dist_sq / bandwidth)
    elif k_type == 'gate':
        dist_l1 = p_distance(y, x, p=1)
        return (1.0 / bandwidth) * (dist_l1 <= bandwidth)
    elif k_type == 'triangle':
        dist_l1 = p_distance(y, x, p=1)
        return (2.0 / bandwidth) * (1.0 - dist_l1 / bandwidth) * (dist_l1 <= bandwidth)
    elif k_type == 'linear':
        return y @ x.T

    return np.zeros((y.shape[0], x.shape[0]))


def nadaraya_watson_estimator(x_test: np.ndarray, x_train: np.ndarray, y_train: np.ndarray, k_type: str, h: float) -> np.ndarray:
    kappa = kernel(x_train, x_test, k_type, h)  # shape (M, N)
    weights = kappa / np.sum(kappa + 1e-10, axis=1, keepdims=True)
    return weights @ y_train


# Task 2: Implement the training and the testing method of Kernel Ridge Regression method.
def training_krr(x_train: np.ndarray, y_train: np.ndarray, k_type: str, h: float, tau: float = 0.1) -> np.ndarray:
    K = kernel(x_train, None, k_type, h)
    # Closed-form solution: (K + tau * I)a = y
    return np.linalg.solve(K + tau * np.eye(K.shape[0]), y_train)


def testing_krr(x_test: np.ndarray, x_train: np.ndarray, alpha: np.ndarray, k_type: str, h: float) -> np.ndarray:
    K_test = kernel(x_train, x_test, k_type, h)
    return K_test @ alpha


# Task 3: Try to learn the KRR model via the stochastic gradient descent (sgd) algorithm
def training_krr_sgd(x_train: np.ndarray,
                     y_train: np.ndarray,
                     k_type: str,
                     h: float,
                     tau: float = 1,
                     epoch: int = 100,
                     batch_size: int = 10,
                     lr: float = 1e-3,
                     r_seed: int = 1) -> np.ndarray:
    num = x_train.shape[0]
    # Initialize alpha to small random values to avoid initial explosion
    rs = np.random.RandomState(r_seed)
    alpha = rs.randn(num, 1) * 0.01
    K = kernel(x_train, None, k_type, h)

    # Use Adam Optimizer to make SGD actually "work" for ill-conditioned KRR
    beta1, beta2, eps = 0.9, 0.999, 1e-8
    m = np.zeros_like(alpha)
    v = np.zeros_like(alpha)
    t = 0
    adam_lr = 0.05  # Custom learning rate better suited for Adam in this scale

    for e in range(epoch):
        indices = rs.permutation(num)

        for i in range(0, num, batch_size):
            idx = indices[i:min(i+batch_size, num)]
            K_batch = K[idx, :]
            y_batch = y_train[idx]

            # Unbiased stochastic gradient of KRR objective
            grad = (2.0 / len(idx)) * K_batch.T @ (K_batch @ alpha - y_batch) + (2.0 * tau / num) * (K @ alpha)

            # Adam step
            t += 1
            m = beta1 * m + (1 - beta1) * grad
            v = beta2 * v + (1 - beta2) * (grad ** 2)
            m_hat = m / (1 - beta1 ** t)
            v_hat = v / (1 - beta2 ** t)

            alpha -= adam_lr * m_hat / (np.sqrt(v_hat) + eps)

    return alpha


# Task 4: Inspired by the learning process of Lasso, develop a coordinate descent method to update alpha iteratively
def training_krr_bcd(x_train: np.ndarray,
                     y_train: np.ndarray,
                     k_type: str,
                     h: float,
                     tau: float = 1,
                     epoch: int = 100,
                     batch_size: int = 10,
                     lr: float = 1e-3,
                     r_seed: int = 1) -> np.ndarray:
    num = x_train.shape[0]
    # Initialize small random
    alpha = np.random.RandomState(r_seed).randn(num, 1) * 0.01

    K = kernel(x_train, None, k_type, h)
    p = K @ alpha  # dynamically maintain p = Ka to reduce complexity

    for e in range(epoch):
        for i in range(0, num, batch_size):
            idx = np.arange(i, min(i + batch_size, num))
            B = len(idx)
            K_B = K[:, idx]  # (N, B)
            K_BB = K[np.ix_(idx, idx)]  # (B, B)

            # Sub-Hessian: avoids calculating full K^2, complexity O(N*B^2)
            # Add small epsilon (1e-8) to ensure it's strictly positive-definite and avoid nan/overflow
            H_BB = K_B.T @ K_B + tau * K_BB + 1e-8 * np.eye(B)

            # Gradient based RHS: complexity O(N*B)
            grad_B = K_B.T @ (p - y_train) + tau * p[idx]

            # Solve block exact minimizer: H_BB * delta = -grad_B
            try:
                delta = np.linalg.solve(H_BB, -grad_B)
            except np.linalg.LinAlgError:
                delta = np.linalg.lstsq(H_BB, -grad_B, rcond=None)[0]

            alpha[idx] += delta
            # dynamically update p: O(N*B)
            p += K_B @ delta

    return alpha


# Testing script
if __name__ == '__main__':
    data = polynomial_data_simulator()
    kernel_types = ['rbf', 'gate', 'triangle', 'linear']
    bandwidths = [0.1, 1, 2, 5]
    for k in range(len(kernel_types)):
        for i in range(len(bandwidths)):
            ker_type = kernel_types[k]
            bw = bandwidths[i]
            y_est0 = nadaraya_watson_estimator(x_test=data['test'][0],
                                               x_train=data['train'][0],
                                               y_train=data['train'][1],
                                               k_type=ker_type, h=bw)
            alpha1 = training_krr(x_train=data['train'][0], y_train=data['train'][1], k_type=ker_type, h=bw)
            y_est1 = testing_krr(x_test=data['test'][0], x_train=data['train'][0], alpha=alpha1, k_type=ker_type, h=bw)
            alpha2 = training_krr_sgd(x_train=data['train'][0], y_train=data['train'][1], k_type=ker_type, h=bw)
            y_est2 = testing_krr(x_test=data['test'][0], x_train=data['train'][0], alpha=alpha2, k_type=ker_type, h=bw)
            alpha3 = training_krr_bcd(x_train=data['train'][0], y_train=data['train'][1], k_type=ker_type, h=bw)
            y_est3 = testing_krr(x_test=data['test'][0], x_train=data['train'][0], alpha=alpha3, k_type=ker_type, h=bw)

            mse0 = mse(data['test'][1], y_est0)
            mse1 = mse(data['test'][1], y_est1)
            mse2 = mse(data['test'][1], y_est2)
            mse3 = mse(data['test'][1], y_est3)

            setting = 'Kernel={}, Bandwidth={:.2f}'.format(
                ker_type, bw)
            result = 'NWKR: MSE={:.4f}, KRR: MSE={:.4f}, \n KRR-sgd: MSE={:.4f}, KRR-bcd: MSE={:.4f}'.format(
                mse0, mse1, mse2, mse3)
            print(setting + ' ' + result)

            plt.figure()
            visualization_points(x=data['train'][0], y=data['train'][1][:, 0], point_type='bx', label='training data')
            visualization_points(x=data['test'][0], y=data['test'][1][:, 0], point_type='kx', label='testing data')
            visualization_curves(weights=data['real'], label='ground truth', curve_type='r-')
            visualization_kernel_curves(alpha=data['train'][1], x_train=data['train'][0],
                                        k_type=ker_type, h=bw, label='nwk', curve_type='g-', normalize=True)
            visualization_kernel_curves(alpha=alpha1, x_train=data['train'][0],
                                        k_type=ker_type, h=bw, label='krr', curve_type='b-')
            visualization_kernel_curves(alpha=alpha2, x_train=data['train'][0],
                                        k_type=ker_type, h=bw, label='krr-sgd', curve_type='k:')
            visualization_kernel_curves(alpha=alpha3, x_train=data['train'][0],
                                        k_type=ker_type, h=bw, label='krr-bcd', curve_type='c-')
            plt.title(result)
            plt.xlabel(setting)
            plt.legend()
            plt.savefig('result_{}_{}.png'.format(k, i))
            plt.close('all')