"""
Introduction to Machine Learning

Lab 3: Regularized linear regression

TODO: Add your information here.
    IMPORTANT: Please ensure this script
    (1) Run script_lab3.py on Python >=3.6;
    (2) No errors;
    (3) Do not add any additional libs or packages
    (4) Finish in tolerable time on a single CPU (e.g., <=10 mins);

Student name(s):黄浩博
Student ID(s):2024201630
"""

import numpy as np
# don't add any other packages


# data simulator and testing function (Don't change them)
def linear_data_simulator(n_train: int = 50,
                          n_test: int = 10,
                          dim: int = 10,
                          v_noise: float = 2,
                          prior: str = 'Gauss',
                          noise: str = 'Gauss',
                          r_seed: int = 42) -> dict:
    """
    Simulate the training and testing data generated by a polynomial model
    :param n_train: the number of training data
    :param n_test: the number of testing data
    :param dim: the dimension of feature
    :param v_noise: the hyper-parameter controlling the variance of data noise
    :param prior: the prior distribution of model parameters, Gauss or Laplace
    :param noise: the noise type, Gauss or Laplace
    :param r_seed: the random seed
    :return:
        a dictionary containing training set, testing set, and the ground truth parameters
    """
    x_train = np.random.RandomState(r_seed).rand(n_train, dim)
    x_test = np.random.RandomState(r_seed).rand(n_test, dim)
    if prior == 'Gauss':
        weights = np.random.RandomState(r_seed).randn(dim, 1)
    else:
        weights = np.random.RandomState(r_seed).laplace(loc=0, scale=1, size=(dim, 1))
    if noise == 'Gauss':
        y_train = x_train @ weights + v_noise * np.random.RandomState(r_seed).randn(n_train, 1)
        y_test = x_test @ weights + v_noise * np.random.RandomState(r_seed).randn(n_test, 1)
    else:
        y_train = x_train @ weights + np.random.RandomState(r_seed).laplace(loc=0, scale=v_noise, size=(n_train, 1))
        y_test = x_test @ weights + np.random.RandomState(r_seed).laplace(loc=0, scale=v_noise, size=(n_test, 1))
    data = {'train': [x_train, y_train],
            'test': [x_test, y_test],
            'real': weights}
    return data


def mse(x: np.ndarray, x_est: np.ndarray) -> float:
    return np.sum((x - x_est) ** 2) / x.shape[0]


def testing(x: np.ndarray, y: np.ndarray, weights: np.ndarray) -> float:
    """
    Compute the MSE of regression based on current model
    :param x: testing data with size (N, )
    :param y: testing label with size (N, 1)
    :param weights: model parameter with size (D, 1)
    :return:
        MSE
    """
    y_est = x @ weights
    return mse(y, y_est)


# Task 1: Implement the OMP algorithm for sparse coding
# which derives the closed form solution directly
def omp(x: np.ndarray, y: np.ndarray, non_zeros: int = 2) -> np.ndarray:
    """
    The OMP algorithm for sparse coding

    min_w ||y - Xw||_2^2, s.t. ||w||_0=2

    :param x: input data with size (N, dim)
    :param y: labels of data with size (N, 1)
    :param non_zeros: the number of nonzero parameters
    :return:
        a weight vector with size (dim, 1)
    """
    # TODO: Change the code below and implement your learning method accordingly
    N, dim = x.shape
    w = np.zeros((dim, 1))
    r = y.copy()  # 初始残差
    S = []  # 支撑集（已选特征索引）

    for _ in range(non_zeros):
        max_corr = -1
        best_d = -1
        # 遍历未选特征，找与残差最相关的
        for d in range(dim):
            if d in S:
                continue
            x_d = x[:, d:d + 1]
            xd_tr = x_d.T @ r
            xd_txd = x_d.T @ x_d
            if xd_txd < 1e-10:  # 避免除以零
                continue
            # 用投影后的相关性作为选择标准
            corr = (xd_tr ** 2) / xd_txd
            if corr > max_corr:
                max_corr = corr
                best_d = d
        if best_d == -1:
            break  # 无有效特征可选

        S.append(best_d)
        # 用当前支撑集做最小二乘更新
        X_S = x[:, S]
        w_S = np.linalg.solve(X_S.T @ X_S + 1e-10 * np.eye(len(S)), X_S.T @ y)
        # 更新残差和权重
        r = y - X_S @ w_S
        w[S] = w_S
    return w


# Task 2: Implement the training function of the ridge regression model,
# which implements the stochastic gradient descent (sgd) algorithm.
def training_sgd(x: np.ndarray,
                 y: np.ndarray,
                 gamma: float,
                 epoch: int = 10,
                 batch_size: int = 10,
                 lr: float = 1e-4,
                 r_seed: int = 1) -> np.ndarray:
    """
    The stochastic gradient descent method of ridge regression.
    :param x: input data with size (N, dim)
    :param y: labels of data with size (N, 1)
    :param gamma: the weight of ridge regularizer
    :param epoch: the number of epochs
    :param batch_size: the batch size for sgd
    :param lr: the learning rate
    :param r_seed: random seed
    :return:
        a weight vector with size (order, 1)
    """
    num = x.shape[0]
    dim = x.shape[1]
    w = np.random.RandomState(r_seed).randn(dim, 1)
    # TODO: Add your code below
    for _ in range(epoch):
        # 打乱数据顺序
        indices = np.random.RandomState(r_seed).permutation(num)
        x_shuffled, y_shuffled = x[indices], y[indices]
        # 分batch训练
        for i in range(0, num, batch_size):
            x_batch = x_shuffled[i:i + batch_size]
            y_batch = y_shuffled[i:i + batch_size]
            # 计算梯度（含正则项）
            y_pred = x_batch @ w
            grad = 2 * x_batch.T @ (y_pred - y_batch) + 2 * gamma * w
            # 更新参数
            w -= lr * grad

    return w


# Task 3: Implement the training function of lasso regression
def soft_thresholding(x: np.ndarray, thres: float) -> np.ndarray:
    """
    The soft-thresholding operator
    :param x: input array with arbitrary size
    :param thres: the threshold
    :return:
        sign(x) * max{0, |x|-thres}
    """
    # TODO: Change the code below and implement your soft-thresholding method
    return  np.sign(x) * np.maximum(0, np.abs(x) - thres)


def training_lasso(x: np.ndarray,
                   y: np.ndarray,
                   gamma: float,
                   iteration: int = 100,
                   r_seed: int = 1) -> np.ndarray:
    """
    The training function of lasso regression model

    min_w ||y - Xw||_2^2 + gamma * ||w||_1

    :param x: input data with size (N, dim)
    :param y: labels of data with size (N, 1)
    :param gamma: the weight of the lasso regularizer
    :param iteration: the number of iterations for soft-thresholding
    :param r_seed: the random seed for initializing model.
    :return:
        a weight vector with size (dim, 1)
    """
    dim = x.shape[1]
    w = np.random.RandomState(r_seed).randn(dim, 1)
    # TODO: Add your code below
    for _ in range(iteration):
        # 逐维度更新（坐标下降法）
        for d in range(dim):
            x_d = x[:, d:d + 1]
            # 计算残差 + 当前特征的贡献（即 y - X_{-d}w_{-d}）
            residual = y - x @ w
            z = x_d.T @ (residual + x_d * w[d])
            norm_xd_sq = x_d.T @ x_d + 1e-10  # 避免除以零
            z /= norm_xd_sq
            # 软阈值更新
            w[d] = soft_thresholding(z, gamma / norm_xd_sq)

    return w


# Task 4: Implement the training function of the linear regression with elastic net regression
def training_elastic(x: np.ndarray,
                     y: np.ndarray,
                     gamma1: float,
                     gamma2: float,
                     iteration: int = 100,
                     r_seed: int = 1) -> np.ndarray:
    """
    The training function of lasso regression model

    min_w ||y - Xw||_2^2 + gamma1 * ||w||_1 + gamma2 * ||w||_2^2

    :param x: input data with size (N, dim)
    :param y: labels of data with size (N, 1)
    :param gamma1: the weight of the lasso regularizer
    :param gamma2: the weight of the ridge regularizer
    :param iteration: the number of iterations for soft-thresholding
    :param r_seed: the random seed for initializing model.
    :return:
        a weight vector with size (dim, 1)
    """
    # TODO: Change the code below and implement your learning method accordingly
    dim = x.shape[1]
    w = np.random.RandomState(r_seed).randn(dim, 1)

    for _ in range(iteration):
        for d in range(dim):
            x_d = x[:, d:d + 1]
            # 计算 y - X_{-d}w_{-d}
            residual = y - x @ w
            r_d = residual + x_d * w[d]
            # 结合L2正则的调整
            xd_trd = x_d.T @ r_d
            norm_adj = x_d.T @ x_d + gamma2 + 1e-10
            z = xd_trd / norm_adj
            # 软阈值（阈值也结合L2正则调整）
            w[d] = soft_thresholding(z, gamma1 / norm_adj)
    return w


# Task 5: Implement the iteratively reweighted least square (IRLS) to solve min_w ||y - Xw||_1
def training_irls(x: np.ndarray,
                  y: np.ndarray,
                  iteration: int = 100,
                  r_seed: int = 1) -> np.ndarray:
    """
    min_w ||y - Xw||_1 (MAE minimization)

    :param x: testing data with size (N, dim)
    :param y: testing label with size (N, 1)
    :param iteration: the number of iterations for soft-thresholding
    :param r_seed: the random seed for initializing model.
    :return:
        a weight vector with size (dim, 1)
    """
    dim = x.shape[1]
    w = np.random.RandomState(r_seed).randn(dim, 1)
    # TODO: Add your code below
    dim = x.shape[1]
    # 初始化：用最小二乘做初始估计（比随机更稳定）
    w = np.linalg.solve(x.T @ x + 1e-10 * np.eye(dim), x.T @ y)

    for _ in range(iteration):
        # 计算残差
        e = y - x @ w
        # 计算权重：1/|e|，加小量避免除以零
        alpha = 1.0 / (np.abs(e) + 1e-8)
        A = np.diag(alpha.flatten())
        # 解加权最小二乘
        w = np.linalg.solve(x.T @ A @ x + 1e-10 * np.eye(dim), x.T @ A @ y)

    return w


# Testing script
if __name__ == '__main__':
    data1 = linear_data_simulator(prior='Gauss', noise='Gauss')
    data2 = linear_data_simulator(prior='Laplace', noise='Gauss')
    data3 = linear_data_simulator(prior='Gauss', noise='Laplace')
    w1 = omp(data2['train'][0], data2['train'][1], non_zeros=4)
    w2 = training_sgd(data1['train'][0], data1['train'][1], gamma=1)
    w3 = training_lasso(data2['train'][0], data2['train'][1], gamma=1)
    w4 = training_elastic(data2['train'][0], data2['train'][1], gamma1=1, gamma2=1)
    w5 = training_irls(data3['train'][0], data3['train'][1])

    mse_w1 = mse(data1['real'], w1)
    mse_w2 = mse(data1['real'], w2)
    mse_w3 = mse(data2['real'], w3)
    mse_w4 = mse(data2['real'], w4)
    mse_w5 = mse(data3['real'], w5)

    mse_y1 = testing(data1['test'][0], data1['test'][1], w1)
    mse_y2 = testing(data1['test'][0], data1['test'][1], w2)
    mse_y3 = testing(data2['test'][0], data2['test'][1], w3)
    mse_y4 = testing(data2['test'][0], data2['test'][1], w4)
    mse_y5 = testing(data3['test'][0], data3['test'][1], w5)

    print('OMP, mse-w={:.4f}, mse-y={:.4f}'.format(mse_w1, mse_y1))
    print('Ridge regression (SGD), mse-w={:.4f}, mse-y={:.4f}'.format(mse_w2, mse_y2))
    print('Lasso regularizer, mse-w={:.4f}, mse-y={:.4f}'.format(mse_w3, mse_y3))
    print('Elastic Net regularizer, mse-w={:.4f}, mse-y={:.4f}'.format(mse_w4, mse_y4))
    print('IRLS, mse-w={:.4f}, mse-y={:.4f}'.format(mse_w5, mse_y5))

